Sprint1 amaituta
Nereee/E4_DB_T4 pull request #1
Opened 2024-04-19 08:27 UTC by hector-elorrieta

2024-04-21 14:47 UTC, Nereee requested changes
Errebisatu behar dituzue foreign key guztien murrizketak. Batzuk ez dituzue aldatu eta arazoak emango dizkizuete datuen eguneraketak egiterakona.

2024-04-22 07:12 UTC, Aitzolgy commented
ez dakit ze foreign key daukadan txarto ez nahiz konturatzen

2024-04-22 07:32 UTC, Nereee commented
Adibidez: ez diozu trataera berdina egiten artista musikari eta artista podcasterrari
Eta horren arira audio eta abesti eta podcastari ere ez. 
Horrela kudeatuko baduzue mahai gaineko aplikaziotik ados, baina agian irizpide bakarra erabiltzea beti izango litzateke onena

2024-04-22 09:12 UTC, Nereee requested changes

2024-04-22 09:12 UTC, Nereee commented on Sphea/Taulen sorrera.sql
> +create table Erreprodukzioak(
Arazoak emango dizkizue Erreprodukzioaken foreign keyen murrizketak!!! Ezingo dituzue bezeroak eta audioak ezabatu... pentsatu zein trataera eman nahi diozuen

2024-04-22 09:31 UTC, Nereee approved these changes

2024-04-22 09:32 UTC, merged